<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Benchmark packages -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />

    <!-- Test packages -->
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="System.Text.Json" Version="10.0.10" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <!-- Future packages for ADO.NET implementation -->
    <!-- <PackageVersion Include="System.Data.Common" Version="4.3.0" /> -->
    
    <!-- Code analyzers -->
    <PackageVersion Include="Roslynator.Analyzers" Version="4.16.1" />
  </ItemGroup>
</Project>
