version: '3.8'

services:
  sqld:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080"
    environment:
      # Enable HTTP API
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
      # Enable CORS for web testing
      - SQLD_HTTP_CORS=true
    volumes:
      # Persist database files
      - sqld_data:/var/lib/sqld
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Alternative sqld with authentication enabled
  sqld-auth:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8081:8080"
    environment:
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
      # JWT key for authentication - generate with: openssl rand -base64 32
      - SQLD_AUTH_JWT_KEY=your-secret-jwt-key-here-replace-with-secure-key
      - SQLD_HTTP_CORS=true
    volumes:
      - sqld_auth_data:/var/lib/sqld
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  sqld_data:
  sqld_auth_data: